/**
 * Every string the interface shows, in English and Spanish.
 *
 * `es` is typed against `en`, so a key added to one language without the other
 * is a compile error rather than an English fallback nobody notices. Keys that
 * end in `_one` / `_other` are plural forms picked by `tn(key, n)`; `{name}`
 * placeholders are filled by `t(key, { name })`.
 *
 * Money is formatted as US dollars in both languages (the app tracks dollars),
 * and the status words that double as data (won, lost …) never go through here.
 */
export const en = {
  // Shared
  bet_one: '{n} bet',
  bet_other: '{n} bets',
  day_one: '{n} day',
  day_other: '{n} days',
  line_one: '{n} line',
  line_other: '{n} lines',
  freeBet_one: '{n} free bet',
  freeBet_other: '{n} free bets',
  'common.optional': 'optional',
  'common.close': 'Close',
  'common.done': 'Done',
  'common.save': 'Save',
  'common.add': 'Add',
  'common.edit': 'Edit',
  'common.delete': 'Delete',
  'common.sure': 'Sure?',
  'common.clickAgain': 'Click again to confirm',
  'common.today': 'today',
  'common.error': 'Something went wrong',

  // Statuses — labels (caps) and words (in sentences)
  'status.won': 'WON',
  'status.lost': 'LOST',
  'status.push': 'PUSH',
  'status.void': 'VOID',
  'status.pending': 'PENDING',
  'statusWord.won': 'won',
  'statusWord.lost': 'lost',
  'statusWord.push': 'push',
  'statusWord.void': 'void',
  'statusWord.pending': 'pending',
  'statusName.won': 'Won',
  'statusName.lost': 'Lost',
  'statusName.push': 'Push',
  'statusName.void': 'Void',
  'statusName.pending': 'Pending',
  'record.w': 'W',
  'record.l': 'L',
  'record.p': 'P',

  // Header
  'header.import': 'Import',
  'header.importTitle': 'Import bets from a CSV file',
  'header.export': 'Export',
  'header.exportTitle': 'Download every bet as a CSV file',
  'header.exportEmpty': 'Nothing to export yet',
  'header.logToday': 'Log today',
  'header.signOut': 'Sign out',
  'header.toLight': 'Switch to light theme',
  'header.toDark': 'Switch to dark theme',
  'header.lang': 'Español',
  'header.langTitle': 'Cambiar a español',
  'sync.synced': 'Synced',
  'sync.syncedTitle': 'All changes are saved to the cloud and shared with your other devices',
  'sync.syncing': 'Syncing…',
  'sync.syncingN': 'Syncing {n}…',
  'sync.syncingTitle': 'Saving queued changes to the cloud…',
  'sync.offline': 'Offline',
  'sync.offlineN': 'Offline · {n} queued',
  'sync.offlineTitle': 'No connection — changes are saved on this device and will sync automatically when you are back online',

  // Hero stats
  'hero.monthPL': '{month} P/L',
  'hero.lifetimePL': 'Lifetime P/L',
  'hero.roi': 'ROI',
  'hero.prevMonth': 'Previous month',
  'hero.nextMonth': 'Next month',
  'hero.noBetsMonth': 'No bets logged this month',
  'hero.pendingSuffix': ' · {n} pending',
  'hero.firstBet': 'Log your first bet to get started',
  'hero.lifetimeSub': '{bets} over {days} since {month}',
  'hero.riding': ' · {n} pending, {amount} riding',
  'hero.roiSub': '{profit} on {staked} staked · {counted}',
  'hero.roiSubset': '{counted} of {total} with a stake',
  'hero.roiNeedsStake': 'Log a bet with its stake to see ROI',
  'hero.roiNone': 'No staked results yet — ROI needs a settled bet with a stake',
  'hero.bonus': '{profit} bonus from {freeBets}',
  'hero.bonusTitle': "Free bets risk nothing, so they can't have a return — their profit is shown apart",
  'hero.smallSample': 'small sample',
  'hero.smallSampleTitle': '{n} settled bets with a stake. Below {min} the number is mostly noise.',
  'hero.avgStake': 'avg {amount}',
  'hero.avgStakeTitle': 'Average stake across bets that recorded one',
  'hero.strike': 'Strike rate',
  'hero.strikeSub': '{w}W–{l}L · n={n}',
  'hero.implied': ' · implied {p}',
  'hero.smallSampleSuffix': ' · small sample',
  'hero.noDecided': 'no decided bets yet',
  'hero.strikeTitle': 'Share of decided bets that won. At your average odds the break-even strike rate is {p} (over the {n} with odds recorded).',
  'hero.strikeTitleNoOdds': 'Share of decided bets that won. Record the odds to see the break-even rate next to it.',
  'hero.greenDays': 'Green days',
  'hero.greenSub': '{w}W–{l}L by day',
  'hero.greenTitle': 'Share of days that ended net positive',
  'hero.noDecisive': 'no decisive days yet',
  'hero.streak': 'Streak',
  'hero.streakGreen': '{days} green running',
  'hero.streakRed': '{days} red running',
  'hero.bestDay': 'Best day',
  'hero.worstDay': 'Worst day',
  'hero.nothingYet': 'nothing yet',
  'hero.drawdown': 'Max drawdown',
  'hero.drawdownSub': 'largest peak-to-trough fall',
  'hero.drawdownNone': 'never below a previous peak',
  'hero.drawdownTitle': 'The deepest your balance has fallen from its highest point',

  // Calendar
  'cal.title': 'Calendar',
  'cal.weekdays': 'Sun,Mon,Tue,Wed,Thu,Fri,Sat',
  'cal.win': 'Win',
  'cal.loss': 'Loss',
  'cal.push': 'Push',
  'cal.pending': 'Pending',
  'cal.none': 'No bets',
  'cal.pushCell': 'PUSH',
  'cal.openCell': 'OPEN',
  'cal.pushTip': 'Push',
  'cal.betsTip': '{n} bets',
  'cal.pendingTip': '{n} pending',
  'cal.emptyTip': 'no bets — click to log',

  // Chart
  'chart.title': 'Balance',
  'chart.range': 'Chart range',
  'chart.all': 'All time',
  'chart.month': 'This month',
  'chart.emptyAll': 'Log at least two days to draw your balance curve.',
  'chart.emptyMonth': 'Log at least two days in {month} to draw a curve.',
  'chart.loading': 'Drawing the chart…',
  'chart.day': 'day',
  'chart.push': 'push',

  // Breakdown
  'bd.title': 'Breakdown',
  'bd.groupBy': 'Group breakdown by',
  'bd.sport': 'Sport',
  'bd.book': 'Book',
  'bd.betType': 'Bet type',
  'bd.sportWord': 'sport',
  'bd.bookWord': 'bookmaker',
  'bd.betTypeWord': 'bet type',
  'bd.empty': 'No bets tagged with a {what} yet. Add one when you log a bet to see how each {what} performs.',
  'bd.pending': ' · {n} pending',
  'bd.noRoi': 'no ROI',
  'bd.noRoiTitle': 'No decided bet here has a real stake, so ROI cannot be computed',
  'bd.roiSubsetTitle': 'ROI covers the {roiBets} of {bets} settled bets that put a stake at risk — the profit above covers all {bets}',
  'bd.roiAllTitle': 'ROI across all {bets} settled bets',
  'bd.roiOn': '{pct} on {staked}',

  // History
  'hist.title': 'History',
  'hist.countOf': '{m} of {bets}',
  'hist.empty': 'No bets logged yet. Hit “Log today” or click a day on the calendar.',
  'hist.noMatch': 'No bets match these filters.',
  'hist.search': 'Search notes, tags, dates…',
  'hist.searchAria': 'Search bets',
  'hist.filterResult': 'Filter by result',
  'hist.filterSport': 'Filter by sport',
  'hist.filterBook': 'Filter by book',
  'hist.allResults': 'All results',
  'hist.allSports': 'All sports',
  'hist.allBooks': 'All books',
  'hist.clear': 'Clear',
  'hist.date': 'Date',
  'hist.result': 'Result',
  'hist.stake': 'Stake',
  'hist.odds': 'Odds',
  'hist.amount': 'Amount',
  'hist.return': 'Return',
  'hist.tags': 'Tags',
  'hist.note': 'Note',
  'hist.actions': 'Actions',
  'hist.editDay': 'Edit this day',
  'hist.editAria': 'Edit {date}',
  'hist.deleteAria': 'Delete bet on {date}',
  'hist.settleAria': 'Settle bet on {date}',
  'hist.markAs': 'Mark as {status}',
  'hist.prevPage': 'Previous page',
  'hist.nextPage': 'Next page',
  'hist.pager': '{from}–{to} of {total}',

  // Day dialog
  'modal.noBets': 'No bets yet',
  'modal.pendingSuffix': ' · {n} pending',
  'modal.dayTotal': 'Day total',
  'modal.noNote': 'no note',
  'modal.riding': '{amount} riding',
  'modal.risked': '{amount} risked',
  'modal.settleGroup': 'Settle this bet',
  'modal.editBet': 'Edit bet',
  'modal.deleteBet': 'Delete bet',
  'modal.addTitle': 'Add a bet',
  'modal.editTitle': 'Edit bet',
  'modal.cancelEdit': 'Cancel edit',
  'modal.resultGroup': 'Result',
  'modal.stake': 'Stake',
  'modal.notRecorded': 'not recorded',
  'modal.odds': 'Odds',
  'modal.oddsOpt': '{format}, optional',
  'modal.profit': 'Profit',
  'modal.amountLost': 'Amount lost',
  'modal.result': 'Result',
  'modal.notYet': 'not yet',
  'modal.stakeReturned': '0.00 (stake returned)',
  'modal.sport': 'Sport',
  'modal.book': 'Book',
  'modal.betType': 'Bet type',
  'modal.note': 'Note',
  'modal.notePlaceholder': 'e.g. morning parlay',
  'modal.hintWon': 'Profit only — what you got back beyond the stake. Add the odds and it fills in.',
  'modal.hintWonOdds': 'Profit only — filled in from stake × (odds − 1). Edit it if the book paid differently.',
  'modal.hintLost': 'Defaults to the stake, since that is what a loss costs.',
  'modal.hintPush': 'A push returns the stake: counts as $0 and stays out of ROI.',
  'modal.hintVoid': 'Cancelled by the book: stake returned, out of the record entirely.',
  'modal.hintPending': 'No result yet. It stays out of P/L, ROI and streaks until you settle it.',

  // App-level messages
  'toast.added': 'Added a bet',
  'toast.loggedPending': 'Logged a pending bet',
  'toast.updated': 'Updated a bet',
  'toast.deleted': 'Deleted a bet',
  'toast.settled': 'Settled as {status}',
  'toast.offline': '{action} — saved on this device, will sync when you’re back online',
  'toast.onDate': '{action} on {date}',
  'toast.exported': 'Exported {bets} to your downloads',
  'toast.importNothing': 'Nothing to import from that file.',
  'toast.imported': 'Imported {bets}',
  'toast.skipped': 'skipped {lines}',
  'toast.noStake': '{n} without a stake',
  'toast.conflict': 'A newer edit from another device was kept',

  // Login
  'login.tagIn': 'Sign in to sync your bets across devices.',
  'login.tagUp': 'Create an account to start tracking.',
  'login.email': 'Email',
  'login.password': 'Password',
  'login.passwordHint': 'At least 6 characters',
  'login.working': 'Working…',
  'login.signIn': 'Sign in',
  'login.create': 'Create account',
  'login.needAccount': 'Need an account? Sign up',
  'login.haveAccount': 'Already have an account? Sign in',
  'login.created': 'Account created. Check your email to confirm, then sign in.',

  // First-run setup screen
  'setup.tag': 'Almost there — connect your Supabase project to enable cross-device sync.',
  'setup.step1': 'Create a free project at {site}.',
  'setup.step2': "Run the SQL in {file} from the project's SQL editor.",
  'setup.step3': 'Copy {example} to {env} and fill in your project URL and anon key (Project Settings → API).',
  'setup.step4': 'Restart the app ({cmd}).',
  'setup.foot': 'Full instructions are in the README.',

  // Quick add
  'quick.fab': 'Quick add',
  'quick.title': 'Quick add',
  'quick.forDate': 'Logged for {date}',
  'quick.stake': 'Stake',
  'quick.odds': 'Odds',
  'quick.saveWon': 'Save as won',
  'quick.hint': 'Tap a result to log it for today. Pending logs it without one.',
  'quick.hintProfit': 'No odds, so type the profit for this win.',

  // Settings
  'header.settings': 'Settings',
  'settings.title': 'Settings',
  'settings.oddsFormat': 'Odds format',
  'settings.oddsHint': 'Changes how odds are shown and typed. They are stored as decimal either way, so switching is free.',
  'settings.defaultStake': 'Default stake',
  'settings.defaultStakeHint': 'Prefilled in quick add. Leave it empty to reuse the last stake.',
  'settings.pending': 'Saved on this device — syncs when you’re back online.',
  'odds.american': 'American',
  'odds.decimal': 'Decimal',
  'odds.fractional': 'Fractional'
} as const

export type StringKey = keyof typeof en

export const es: Record<StringKey, string> = {
  bet_one: '{n} apuesta',
  bet_other: '{n} apuestas',
  day_one: '{n} día',
  day_other: '{n} días',
  line_one: '{n} línea',
  line_other: '{n} líneas',
  freeBet_one: '{n} apuesta gratis',
  freeBet_other: '{n} apuestas gratis',
  'common.optional': 'opcional',
  'common.close': 'Cerrar',
  'common.done': 'Listo',
  'common.save': 'Guardar',
  'common.add': 'Añadir',
  'common.edit': 'Editar',
  'common.delete': 'Eliminar',
  'common.sure': '¿Seguro?',
  'common.clickAgain': 'Pulsa otra vez para confirmar',
  'common.today': 'hoy',
  'common.error': 'Algo ha fallado',

  'status.won': 'GANADA',
  'status.lost': 'PERDIDA',
  'status.push': 'PUSH',
  'status.void': 'NULA',
  'status.pending': 'PENDIENTE',
  'statusWord.won': 'ganada',
  'statusWord.lost': 'perdida',
  'statusWord.push': 'push',
  'statusWord.void': 'nula',
  'statusWord.pending': 'pendiente',
  'statusName.won': 'Ganadas',
  'statusName.lost': 'Perdidas',
  'statusName.push': 'Push',
  'statusName.void': 'Nulas',
  'statusName.pending': 'Pendientes',
  'record.w': 'G',
  'record.l': 'P',
  'record.p': 'E',

  'header.import': 'Importar',
  'header.importTitle': 'Importar apuestas desde un CSV',
  'header.export': 'Exportar',
  'header.exportTitle': 'Descargar todas las apuestas en CSV',
  'header.exportEmpty': 'Aún no hay nada que exportar',
  'header.logToday': 'Registrar hoy',
  'header.signOut': 'Salir',
  'header.toLight': 'Cambiar a tema claro',
  'header.toDark': 'Cambiar a tema oscuro',
  'header.lang': 'English',
  'header.langTitle': 'Switch to English',
  'sync.synced': 'Sincronizado',
  'sync.syncedTitle': 'Todos los cambios están guardados en la nube y compartidos con tus otros dispositivos',
  'sync.syncing': 'Sincronizando…',
  'sync.syncingN': 'Sincronizando {n}…',
  'sync.syncingTitle': 'Guardando en la nube los cambios en cola…',
  'sync.offline': 'Sin conexión',
  'sync.offlineN': 'Sin conexión · {n} en cola',
  'sync.offlineTitle': 'Sin conexión: los cambios se guardan en este dispositivo y se sincronizarán solos al volver la conexión',

  'hero.monthPL': 'P/L de {month}',
  'hero.lifetimePL': 'P/L total',
  'hero.roi': 'ROI',
  'hero.prevMonth': 'Mes anterior',
  'hero.nextMonth': 'Mes siguiente',
  'hero.noBetsMonth': 'Sin apuestas este mes',
  'hero.pendingSuffix': ' · {n} pendientes',
  'hero.firstBet': 'Registra tu primera apuesta para empezar',
  'hero.lifetimeSub': '{bets} en {days} desde {month}',
  'hero.riding': ' · {n} pendientes, {amount} en juego',
  'hero.roiSub': '{profit} sobre {staked} apostados · {counted}',
  'hero.roiSubset': '{counted} de {total} con stake',
  'hero.roiNeedsStake': 'Registra una apuesta con su stake para ver el ROI',
  'hero.roiNone': 'Aún no hay resultados con stake: el ROI necesita una apuesta resuelta con stake',
  'hero.bonus': '{profit} de bonus por {freeBets}',
  'hero.bonusTitle': 'Las apuestas gratis no arriesgan nada, así que no tienen retorno: su ganancia se muestra aparte',
  'hero.smallSample': 'muestra pequeña',
  'hero.smallSampleTitle': '{n} apuestas resueltas con stake. Por debajo de {min} la cifra es sobre todo ruido.',
  'hero.avgStake': 'media {amount}',
  'hero.avgStakeTitle': 'Stake medio de las apuestas que lo registraron',
  'hero.strike': 'Acierto',
  'hero.strikeSub': '{w}G–{l}P · n={n}',
  'hero.implied': ' · implícita {p}',
  'hero.smallSampleSuffix': ' · muestra pequeña',
  'hero.noDecided': 'aún no hay apuestas decididas',
  'hero.strikeTitle': 'Porcentaje de apuestas decididas que ganaron. A tu cuota media, el acierto de equilibrio es {p} (sobre las {n} con cuota registrada).',
  'hero.strikeTitleNoOdds': 'Porcentaje de apuestas decididas que ganaron. Registra las cuotas para ver al lado el acierto de equilibrio.',
  'hero.greenDays': 'Días en verde',
  'hero.greenSub': '{w}G–{l}P por día',
  'hero.greenTitle': 'Porcentaje de días que acabaron en positivo',
  'hero.noDecisive': 'aún no hay días decisivos',
  'hero.streak': 'Racha',
  'hero.streakGreen': '{days} en verde seguidos',
  'hero.streakRed': '{days} en rojo seguidos',
  'hero.bestDay': 'Mejor día',
  'hero.worstDay': 'Peor día',
  'hero.nothingYet': 'nada aún',
  'hero.drawdown': 'Caída máxima',
  'hero.drawdownSub': 'mayor caída desde un máximo',
  'hero.drawdownNone': 'nunca por debajo de un máximo anterior',
  'hero.drawdownTitle': 'Lo más que ha caído tu balance desde su punto más alto',

  'cal.title': 'Calendario',
  'cal.weekdays': 'Dom,Lun,Mar,Mié,Jue,Vie,Sáb',
  'cal.win': 'Ganado',
  'cal.loss': 'Perdido',
  'cal.push': 'Push',
  'cal.pending': 'Pendiente',
  'cal.none': 'Sin apuestas',
  'cal.pushCell': 'PUSH',
  'cal.openCell': 'ABIERTO',
  'cal.pushTip': 'Push',
  'cal.betsTip': '{n} apuestas',
  'cal.pendingTip': '{n} pendientes',
  'cal.emptyTip': 'sin apuestas — pulsa para registrar',

  'chart.title': 'Balance',
  'chart.range': 'Rango del gráfico',
  'chart.all': 'Todo',
  'chart.month': 'Este mes',
  'chart.emptyAll': 'Registra al menos dos días para dibujar tu curva de balance.',
  'chart.emptyMonth': 'Registra al menos dos días en {month} para dibujar una curva.',
  'chart.loading': 'Dibujando el gráfico…',
  'chart.day': 'día',
  'chart.push': 'push',

  'bd.title': 'Desglose',
  'bd.groupBy': 'Agrupar el desglose por',
  'bd.sport': 'Deporte',
  'bd.book': 'Casa',
  'bd.betType': 'Tipo',
  'bd.sportWord': 'deporte',
  'bd.bookWord': 'casa de apuestas',
  'bd.betTypeWord': 'tipo de apuesta',
  'bd.empty': 'Aún no hay apuestas etiquetadas con {what}. Añádelo al registrar una apuesta para ver cómo rinde cada {what}.',
  'bd.pending': ' · {n} pendientes',
  'bd.noRoi': 'sin ROI',
  'bd.noRoiTitle': 'Ninguna apuesta decidida de este grupo tiene un stake real, así que no se puede calcular el ROI',
  'bd.roiSubsetTitle': 'El ROI cubre las {roiBets} de {bets} apuestas resueltas que arriesgaron un stake; la ganancia de arriba cubre las {bets}',
  'bd.roiAllTitle': 'ROI sobre las {bets} apuestas resueltas',
  'bd.roiOn': '{pct} sobre {staked}',

  'hist.title': 'Historial',
  'hist.countOf': '{m} de {bets}',
  'hist.empty': 'Aún no hay apuestas. Pulsa «Registrar hoy» o un día del calendario.',
  'hist.noMatch': 'Ninguna apuesta coincide con estos filtros.',
  'hist.search': 'Buscar notas, etiquetas, fechas…',
  'hist.searchAria': 'Buscar apuestas',
  'hist.filterResult': 'Filtrar por resultado',
  'hist.filterSport': 'Filtrar por deporte',
  'hist.filterBook': 'Filtrar por casa',
  'hist.allResults': 'Todos los resultados',
  'hist.allSports': 'Todos los deportes',
  'hist.allBooks': 'Todas las casas',
  'hist.clear': 'Limpiar',
  'hist.date': 'Fecha',
  'hist.result': 'Resultado',
  'hist.stake': 'Stake',
  'hist.odds': 'Cuota',
  'hist.amount': 'Importe',
  'hist.return': 'Retorno',
  'hist.tags': 'Etiquetas',
  'hist.note': 'Nota',
  'hist.actions': 'Acciones',
  'hist.editDay': 'Editar este día',
  'hist.editAria': 'Editar {date}',
  'hist.deleteAria': 'Eliminar la apuesta del {date}',
  'hist.settleAria': 'Resolver la apuesta del {date}',
  'hist.markAs': 'Marcar como {status}',
  'hist.prevPage': 'Página anterior',
  'hist.nextPage': 'Página siguiente',
  'hist.pager': '{from}–{to} de {total}',

  'modal.noBets': 'Sin apuestas',
  'modal.pendingSuffix': ' · {n} pendientes',
  'modal.dayTotal': 'Total del día',
  'modal.noNote': 'sin nota',
  'modal.riding': '{amount} en juego',
  'modal.risked': '{amount} arriesgados',
  'modal.settleGroup': 'Resolver esta apuesta',
  'modal.editBet': 'Editar apuesta',
  'modal.deleteBet': 'Eliminar apuesta',
  'modal.addTitle': 'Añadir apuesta',
  'modal.editTitle': 'Editar apuesta',
  'modal.cancelEdit': 'Cancelar edición',
  'modal.resultGroup': 'Resultado',
  'modal.stake': 'Stake',
  'modal.notRecorded': 'sin registrar',
  'modal.odds': 'Cuota',
  'modal.oddsOpt': '{format}, opcional',
  'modal.profit': 'Ganancia',
  'modal.amountLost': 'Importe perdido',
  'modal.result': 'Resultado',
  'modal.notYet': 'todavía no',
  'modal.stakeReturned': '0.00 (stake devuelto)',
  'modal.sport': 'Deporte',
  'modal.book': 'Casa',
  'modal.betType': 'Tipo de apuesta',
  'modal.note': 'Nota',
  'modal.notePlaceholder': 'p. ej. combinada de la mañana',
  'modal.hintWon': 'Solo la ganancia: lo que recuperaste más allá del stake. Añade la cuota y se rellena solo.',
  'modal.hintWonOdds': 'Solo la ganancia, calculada como stake × (cuota − 1). Edítala si la casa pagó distinto.',
  'modal.hintLost': 'Por defecto, el stake: es lo que cuesta una apuesta perdida.',
  'modal.hintPush': 'Un push devuelve el stake: cuenta como $0 y queda fuera del ROI.',
  'modal.hintVoid': 'Anulada por la casa: stake devuelto y fuera del registro.',
  'modal.hintPending': 'Sin resultado todavía. Queda fuera de P/L, ROI y rachas hasta que la resuelvas.',

  'toast.added': 'Apuesta añadida',
  'toast.loggedPending': 'Apuesta pendiente registrada',
  'toast.updated': 'Apuesta actualizada',
  'toast.deleted': 'Apuesta eliminada',
  'toast.settled': 'Resuelta como {status}',
  'toast.offline': '{action} — guardada en este dispositivo, se sincronizará al volver la conexión',
  'toast.onDate': '{action} el {date}',
  'toast.exported': '{bets} exportadas a tus descargas',
  'toast.importNothing': 'No hay nada que importar en ese archivo.',
  'toast.imported': '{bets} importadas',
  'toast.skipped': '{lines} omitidas',
  'toast.noStake': '{n} sin stake',
  'toast.conflict': 'Se ha conservado una edición más reciente de otro dispositivo',

  'login.tagIn': 'Inicia sesión para sincronizar tus apuestas entre dispositivos.',
  'login.tagUp': 'Crea una cuenta para empezar a registrar.',
  'login.email': 'Correo',
  'login.password': 'Contraseña',
  'login.passwordHint': 'Al menos 6 caracteres',
  'login.working': 'Un momento…',
  'login.signIn': 'Entrar',
  'login.create': 'Crear cuenta',
  'login.needAccount': '¿No tienes cuenta? Regístrate',
  'login.haveAccount': '¿Ya tienes cuenta? Entra',
  'login.created': 'Cuenta creada. Confírmala desde tu correo y luego entra.',

  'setup.tag': 'Casi listo: conecta tu proyecto de Supabase para sincronizar entre dispositivos.',
  'setup.step1': 'Crea un proyecto gratuito en {site}.',
  'setup.step2': 'Ejecuta el SQL de {file} desde el editor SQL del proyecto.',
  'setup.step3': 'Copia {example} a {env} y rellena la URL del proyecto y la clave anon (Project Settings → API).',
  'setup.step4': 'Reinicia la app ({cmd}).',
  'setup.foot': 'Las instrucciones completas están en el README.',

  'quick.fab': 'Registro rápido',
  'quick.title': 'Registro rápido',
  'quick.forDate': 'Se registra el {date}',
  'quick.stake': 'Stake',
  'quick.odds': 'Cuota',
  'quick.saveWon': 'Guardar como ganada',
  'quick.hint': 'Toca un resultado para registrarla hoy. Pendiente la registra sin resultado.',
  'quick.hintProfit': 'Sin cuota, así que escribe la ganancia de esta apuesta.',

  'header.settings': 'Ajustes',
  'settings.title': 'Ajustes',
  'settings.oddsFormat': 'Formato de cuotas',
  'settings.oddsHint': 'Cambia cómo se muestran y se escriben las cuotas. Se guardan siempre en decimal, así que cambiar no cuesta nada.',
  'settings.defaultStake': 'Stake por defecto',
  'settings.defaultStakeHint': 'Se rellena en el registro rápido. Déjalo vacío para repetir el último stake.',
  'settings.pending': 'Guardado en este dispositivo: se sincronizará al volver la conexión.',
  'odds.american': 'Americana',
  'odds.decimal': 'Decimal',
  'odds.fractional': 'Fraccionaria'
}
